version: "3"
services:
  ganache:
    build:
      context: .
      dockerfile: Dockerfile.ganache
    ports:
      - "8545:8545"
  dapp:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - ganache

  react:
    build: ./reactjs
    volumes:
      - ./reactjs:/app
      - /app/node_modules
    ports:
      - "3002:3000"
    depends_on:
      - dapp
