version: "3"
services:
  ganache:
    build:
      context: ./ganache
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
  expressjs:
    build:
      context: ./expressjs
      dockerfile: Dockerfile
    volumes:
      - ./expressjs:/app
    ports:
      - "4000:4000"
    depends_on:
      - ganache

  reactjs:
    build:
      context: ./reactjs
      dockerfile: Dockerfile
    volumes:
      - ./reactjs:/app
    ports:
      - "3000:3000"
    depends_on:
      - expressjs
    stdin_open: true
